version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:pass@db:5432/signalmaster
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=signalmaster
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
