app = "signalmaster-pro-fastapi"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = ""

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
